[alias]
test-unit       = "test --release tests::unit"
test-roundtrip  = "test --release tests::roundtrip"
test-throughput = "test --release --features throughput tests::throughput -- --nocapture --test-threads=1"

# Platform-specific build flags

[target.aarch64-apple-darwin]
rustflags = [
    "-C", "target-cpu=native"
]

[target.x86_64-apple-darwin]
rustflags = [
    "-C", "target-cpu=native"
]
