[alias]
test-unit       = "test --release unit"
test-roundtrip  = "test --release roundtrip"
test-throughput = "test --release --features throughput throughput -- --nocapture --test-threads=1"

# Platform-specific build flags

[target.aarch64-apple-darwin]
rustflags = [
    "-C", "target-cpu=native"
]

[target.x86_64-apple-darwin]
rustflags = [
    "-C", "target-cpu=native"
]
